name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.7'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: Wild-Area/vs-recorder-data
          path: ./data

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
        working-directory: ./data
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: ./data/.git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('./data/.lfs-assets-id') }}-v1
      - name: Git LFS Pull
        run: git lfs pull
        working-directory: ./data

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - run: julia .github/workflows/prepare-test.jl
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
